package auth

// User represents a user in the domain
type User struct {
	Owner               string
	Name                string
	CreatedTime         string
	UpdatedTime         string
	ID                  string
	Type                string
	Password            string
	PasswordSalt        string
	DisplayName         string
	FirstName           string
	LastName            string
	Avatar              string
	PermanentAvatar     string
	Email               string
	EmailVerified       bool
	Phone               string
	PhoneVerified       bool
	CountryCode         string
	Region              string
	Location            string
	Address             []string
	Affiliation         string
	Title               string
	IdCardType          string
	IdCard              string
	Homepage            string
	Bio                 string
	Language            string
	Gender              string
	Birthday            string
	Education           string
	Score               int
	Karma               int
	Ranking             int
	IsOnline            bool
	IsAdmin             bool
	IsGlobalAdmin       bool
	IsForbidden         bool
	IsDeleted           bool
	SignupApplication   string
	Hash                string
	PreHash             string
	CreatedIP           string
	LastSigninTime      string
	LastSigninIP        string
	GitHub              string
	Google              string
	QQ                  string
	WeChat              string
	Facebook            string
	DingTalk            string
	Weibo               string
	Gitee               string
	LinkedIn            string
	Wecom               string
	Lark                string
	Gitlab              string
	ADFS                string
	Baidu               string
	Alipay              string
	Casdoor             string
	Infoflow            string
	Apple               string
	AzureAD             string
	Slack               string
	Steam               string
	Bilibili            string
	Okta                string
	Douyin              string
	Line                string
	Amazon              string
	Instagram           string
	TikTok              string
	Dropbox             string
	Yahoo               string
	Yandex              string
	StackOverflow       string
	Tumblr              string
	Mailru              string
	Battle              string
	Uber                string
	NextCloud           string
	Naver               string
	Kakao               string
	VK                  string
	Patreon             string
	Custom              string
	Ldap                string
	Properties          map[string]string
	Roles               []*Role
	Permissions         []*Permission
	Groups              []string
	LastSigninWrongTime string
	SigninWrongTimes    int
	Tag                 string
	ManagedAccounts     []ManagedAccount
}
